import { test, expect, event } from './setup/fixtures'
const api = 'https://ticketremasterapi.invalid'
const events = Array.from({ length: 10 }, (_, index) => ({ ...event, eventId: `evt_${String(index + 1).padStart(3, '0')}`, name: index === 0 ? 'Taylor Swift' : `Fixture Event ${index + 1}`, eventDate: index === 0 ? '2030-06-15T10:00:00Z' : '2030-06-16T10:00:00Z' }))

test.describe('Events Flow', () => {
  test.beforeEach(async ({ page }) => {
    await page.route(`${api}/events?*`, route => route.fulfill({ json: { data: { events, pagination: { total: 10, limit: 10, page: 1 } } } }))
  })
  test('should show events and open the selected event details', async ({ page }) => {
    await page.goto('/events')
    await page.locator('.event-card-feature').getByRole('button', { name: 'Get Tickets' }).click()
    await expect(page).toHaveURL('/events/evt_001')
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Taylor Swift')
    await expect(page.locator('.event-page')).toContainText('National Stadium')
    await expect(page.getByRole('button', { name: /Select.*Seat|Get Tickets|Book/i })).toBeVisible()
  })
  test('should show an unavailable state for a missing event (404)', async ({ page }) => {
    await page.route(`${api}/events/missing`, route => route.fulfill({ status: 404, json: { error: { code: 'NOT_FOUND' } } }))
    await page.goto('/events/missing')
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('We couldn’t find that event.')
    await page.getByRole('button', { name: /Back|Browse/ }).click()
    await expect(page).toHaveURL('/events')
  })
  test('should toggle the featured favorite with the keyboard without opening its event', async ({ page }) => {
    await page.goto('/events')
    const favorite = page.getByRole('button', { name: 'Favorite Taylor Swift', exact: true })
    await favorite.focus()
    await favorite.press('Enter')
    await expect(page).toHaveURL('/events')
    await expect(favorite).toHaveAttribute('aria-pressed', 'true')
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('favoriteEvents')!))).toEqual(['evt_001'])
    await page.getByRole('button', { name: 'Favorites', exact: true }).click()
    await expect(page.locator('.event-card')).toHaveCount(1)
    await favorite.press('Space')
    await expect(page).toHaveURL('/events')
    await expect(page.getByRole('heading', { name: 'No events found.' })).toBeVisible()
  })
  test('should filter events by an inclusive date range and clear the filter', async ({ page }) => {
    await page.goto('/events')
    await page.getByLabel('From date').fill('2030-06-15')
    await page.getByLabel('To date').fill('2030-06-15')
    await expect(page.locator('.event-card')).toHaveCount(1)
    await expect(page.locator('.event-card')).toContainText('Taylor Swift')
    await page.getByLabel('To date').fill('2030-06-16')
    await expect(page.locator('.event-card')).toHaveCount(10)
    await page.getByLabel('From date').fill('2030-06-17')
    await expect(page.getByRole('heading', { name: 'No events found.' })).toBeVisible()
    await page.getByLabel('From date').fill('')
    await page.getByLabel('To date').fill('')
    await expect(page.locator('.event-card')).toHaveCount(10)
  })
  test('should render every event returned for the current page', async ({ page }) => {
    await page.goto('/events')
    await expect(page.locator('.event-card h2, .event-card h3')).toHaveText(events.map(item => item.name))
    await expect(page.getByRole('button', { name: 'Next', exact: true })).toHaveCount(0)
  })
})


test('date filters match the displayed Singapore calendar day across UTC midnight', async ({ page }) => {
  await page.route(`${api}/events?*`, route => route.fulfill({ json: { data: { events: [{ ...event, eventDate: '2030-06-15T19:00:00Z' }] } } }))
  await page.goto('/events')
  await page.getByLabel('From date').fill('2030-06-15')
  await page.getByLabel('To date').fill('2030-06-15')
  await expect(page.locator('.event-card')).toHaveCount(0)
  await page.getByLabel('From date').fill('2030-06-16')
  await page.getByLabel('To date').fill('2030-06-16')
  await expect(page.locator('.event-card')).toHaveCount(1)
  await expect(page.locator('.event-card-feature')).toContainText('16 Jun 2030')
})
